/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class top_laonaailifa_jdk_java_thread_YuThread */

#ifndef _Included_top_laonaailifa_jdk_java_thread_YuThread
#define _Included_top_laonaailifa_jdk_java_thread_YuThread
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     top_laonaailifa_jdk_java_thread_YuThread
 * Method:    callback
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_top_laonaailifa_jdk_java_thread_YuThread_callback
  (JNIEnv *, jobject);

/*
 * Class:     top_laonaailifa_jdk_java_thread_YuThread
 * Method:    start0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_top_laonaailifa_jdk_java_thread_YuThread_start0
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
